import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="page-bg">
          {children}

          {/* Top indicator */}
          <div
            style={{
              position: "fixed",
              top: "8px",
              right: "-8px",
              color: "rgba(255,140,0,0.8)",
              textShadow: "0 0 8px rgba(255,140,0,0.6)",
              pointerEvents: "none",
              zIndex: 9999,
              fontSize: "0.75rem",
            }}
          >
            ▲
          </div>

          {/* Bottom indicator */}
          <div
            style={{
              position: "fixed",
              bottom: "8px",
              right: "2px",
              color: "rgba(255,140,0,0.8)",
              textShadow: "0 0 8px rgba(255,140,0,0.6)",
              pointerEvents: "none",
              zIndex: 9999,
              fontSize: "0.75rem",
            }}
          >
            ▼
          </div>
        </div>
      </body>
    </html>
  );
}